### ISSUE TITLE
Maven repository is not updated

### ISSUE THREAD

**Issue by Abu-Abdullah** [RishiGupta12/SerialPundit#16]
Hi,

i have seen in the documentation that maven link is:
```
<dependency>
            <groupId>com.embeddedunveiled</groupId>
            <artifactId>scm</artifactId>
            <version>1.0.4</version>
        </dependency>
```

but this is not correct, the last version is 1.0.3

the other link with 1.0.4 is 
org.bidib.com.embeddedunveiled

also the latest build in the prebuild folder is very new and v1.0.4 is back to Nov 2016

I hope Maven repo is updated with the latest always

**Comment by RishiGupta12** [comment]
I have completely redesigned, improved quality, added features etc and renamed  the project from scm to sp. Please use jar files provided in this repository only. Maven integration will take some time.
