### ISSUE TITLE
Add support for armv7 to sp-usb.jar

### ISSUE THREAD

**Issue by akuhtz** [RishiGupta12/SerialPundit#21]
Hi Rishi,

Could you add support for ARMv7 to sp-usb.jar? Running on a Bananapi it complains about missing spusblnxarmv7hf.so . 

Regards,
Andreas

**Comment by akuhtz** [comment]
Hi Rishi,

The same error happens on a Raspberry 3. 
BTW: Open the serial port works fine.

**Comment by Remboooo** [comment]
I'm running into the same issue. When I figured I would compile the native part for this platform myself, I could not find any native sources in this repo. Is that intentional? The JNI build scripts just produce the headers, nothing else.

**Comment by RishiGupta12** [comment]
May you please try new sp-usb.jar file https://github.com/RishiGupta12/SerialPundit/tree/master/prebuilt-release
I have added armv7hf shared library file.

**Comment by akuhtz** [comment]
Works fine on a Raspberry 3 now. Thank you 🥇
