### ISSUE TITLE
SerialComManager.setRTS() causes exception

### ISSUE THREAD

**Issue by akuhtz** [RishiGupta12/SerialPundit#26]
Hi Rishi,

I'm running Test23 under Win7 64bit and it causes an exception when setRTS() is called (scm.setRTS(DTE, true); )

```
com.serialpundit.core.SerialComException: The data area passed to a system call is too small.

	at com.serialpundit.serial.internal.SerialComPortJNIBridge.setRTS(Native Method)
	at com.serialpundit.serial.SerialComManager.setRTS(SerialComManager.java:1505)
	at test23.Test23.main(Test23.java:65)
ERROR: JDWP Unable to get JNI 1.2 environment, jvm->GetEnv() return code = -2
JDWP exit error AGENT_ERROR_NO_JNI_ENV(183):  [util.c:840]

```

**Comment by RishiGupta12** [comment]
Looks like it is JVM side thing not serialpundit. Are you debugging something using a debugger.

http://bugs.java.com/view_bug.do?bug_id=6476706
https://stackoverflow.com/questions/27500398/debugging-java-in-eclipse-error
https://www.eclipse.org/forums/index.php/t/1069715/

**Comment by akuhtz** [comment]
Hi Rishi,

Even from commandline it throws the same error:
```
D:\github\serial-communication-manager\prebuilt-release>java -classpath sp-core.jar;sp-tty.jar;. test23.Test23
com.serialpundit.core.SerialComException: The parameter is incorrect.

        at com.serialpundit.serial.internal.SerialComPortJNIBridge.setRTS(Native Method)
        at com.serialpundit.serial.SerialComManager.setRTS(SerialComManager.java:1505)
        at test23.Test23.main(Test23.java:65)
```

**Comment by RishiGupta12** [comment]
Any change in driver or hardware.

**Comment by akuhtz** [comment]
Hi Rishi,
Will check on linux.

**Comment by akuhtz** [comment]
Hi Rishi,
I tested on a raspi 3 and it worked without an exception.

**Comment by RishiGupta12** [comment]
Found one more info https://stackoverflow.com/questions/2225737/error-jdwp-unable-to-get-jni-1-2-environment

Seems like it should have been fixed already by JVM/Windows/IDE etc. Should we close it.

**Comment by akuhtz** [comment]
I see a similar exception with SPSW under Windows. Lets close it.
