### ISSUE TITLE
serial library seems to be missing from maven 

### ISSUE THREAD

**Issue by femans** [RishiGupta12/SerialPundit#28]
Hi, I tried to import core and serial using gradle from the Maven repository.
I could only find the core module, not serial, in the repo.
Is this by design? Or can you add it?
Thank you for your interest.

**Comment by femans** [comment]
fixed it by using sp-tty

**Comment by RishiGupta12** [comment]
Please use jar files only from github https://github.com/RishiGupta12/SerialPundit/tree/master/prebuilt-release folder. Do not use maven releases (they are very very old).
