### ISSUE TITLE
Native Library /tmp/sp_tuartx1/spcomlnxx64.so already loaded in another classloader with servlet 

### ISSUE THREAD

**Issue by rucko24** [RishiGupta12/SerialPundit#30]
Regards, how are you? I have a web application with java using vaadin framework, when I make a change in my code and restart my servlet I get this log, Everything returns to work correctly when, to completely my jetty or wildfly server, and I start again

`com.serialpundit.core.SerialComException: Native Library /tmp/sp_tuartx1/spcomlnxx64.so already loaded in another classloader
	at com.serialpundit.serial.internal.SerialComPortJNIBridge.loadNativeLibrary(SerialComPortJNIBridge.java:395)
	at com.serialpundit.serial.SerialComManager.<init>(SerialComManager.java:382)`

**Comment by RishiGupta12** [comment]
- Are you using hot deployment at server.
- Try this constructor : SerialComManager(String loadedLibName, String directoryPath, final boolean createDirectory, boolean hotDeploy)

Please use google group.
