### ISSUE TITLE
Get InputStream from SerialComManager

### ISSUE THREAD

**Issue by russellhoff** [RishiGupta12/SerialPundit#32]
I'm about to make use of [marine api](https://github.com/ktuukkan/marine-api/). 

To start off, an InputStream is needed, but I don't know whether the first line is correct or not:
```
InputStream is = (InputStream) scm.getIOStreamInstance(SerialComManager.InputStream, handleGps, SMODE.NONBLOCKING);
SentenceReader sr = new SentenceReader(is);
sr.addSentenceListener(this);
sr.start();
```

If not, is there any other way?

Thanks!

**Comment by RishiGupta12** [comment]
Example1: https://github.com/RishiGupta12/SerialPundit/tree/master/applications/byte-stream-binary-jar-integrate
Example2: https://github.com/RishiGupta12/SerialPundit/blob/master/tests/test53-byteStream/src/test53/Test53.java
Example3: https://github.com/RishiGupta12/SerialPundit/blob/master/tests/test54-closeport-Blockingread/src/test54/Test54.java

Expect some delay in my responses as I will be travelling to other country for vacations.

**Comment by russellhoff** [comment]
Thank you for your help @RishiGupta12, I hope those examples are enough.

**Comment by russellhoff** [comment]
I've taken a look at the examples, and `SerialComInByteStream` is always used. What I need is to get a `java.io.InputStream`. Is a simple cast enough (`InputStream is = (InputStream) scm.getIOStreamInstance(SerialComManager.InputStream, handleGps, SMODE.NONBLOCKING);`)?

**Comment by RishiGupta12** [comment]
1. SerialComInByteStream extends InputStream in serial pundit. Any methods of InputStream are supported by SerialComInByteStream class (line 35 https://github.com/RishiGupta12/SerialPundit/blob/master/modules/serial/src/com/serialpundit/serial/SerialComInByteStream.java#L35)
